"""add_quantity_constraints

Revision ID: 1d69bd11fd11
Revises: 37d565d9c643
Create Date: 2024-12-22 20:58:55.151336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d69bd11fd11"
down_revision: Union[str, None] = "37d565d9c643"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
