"""initial

Revision ID: 37d565d9c643
Revises: 
Create Date: 2024-12-22 20:55:25.302813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37d565d9c643"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    with op.batch_alter_table("cart", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cart_id", sa.Integer(), nullable=False))
        batch_op.drop_column("id")
        batch_op.drop_column("added_date")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("photo", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )
        batch_op.alter_column("price", existing_type=sa.FLOAT(), nullable=True)
        batch_op.drop_column("is_available")
        batch_op.drop_column("created_at")
        batch_op.drop_column("image_url")
        batch_op.drop_column("photo_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("location_lat", sa.Float(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("location_lon", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("age", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("photo_id", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("reg_date", sa.DateTime(), nullable=True)
        )
        batch_op.drop_column("is_active")
        batch_op.drop_column("registration_date")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("registration_date", sa.DATETIME(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_active", sa.BOOLEAN(), nullable=True)
        )
        batch_op.drop_column("reg_date")
        batch_op.drop_column("photo_id")
        batch_op.drop_column("age")
        batch_op.drop_column("location_lon")
        batch_op.drop_column("location_lat")
        batch_op.drop_column("email")
        batch_op.drop_column("phone")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("photo_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column("image_url", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("created_at", sa.DATETIME(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("is_available", sa.BOOLEAN(), nullable=True)
        )
        batch_op.alter_column(
            "price", existing_type=sa.FLOAT(), nullable=False
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("quantity")
        batch_op.drop_column("photo")

    with op.batch_alter_table("cart", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("added_date", sa.DATETIME(), nullable=True)
        )
        batch_op.add_column(sa.Column("id", sa.INTEGER(), nullable=False))
        batch_op.drop_column("cart_id")

    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=True),
        sa.Column("location_lat", sa.FLOAT(), nullable=True),
        sa.Column("location_lon", sa.FLOAT(), nullable=True),
        sa.Column("age", sa.INTEGER(), nullable=True),
        sa.Column("photo_id", sa.VARCHAR(), nullable=True),
        sa.Column("last_updated", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###
