"""add orders tables

Revision ID: 6e428f6ebee1
Revises: d53fc690492c
Create Date: 2024-12-24 21:32:50.173988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e428f6ebee1"
down_revision: Union[str, None] = "d53fc690492c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "PROCESSING",
                "CONFIRMED",
                "DELIVERING",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=True,
        ),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("delivery_address", sa.String(), nullable=True),
        sa.Column(
            "payment_method",
            sa.Enum("CASH", "CARD", "ONLINE", name="paymentmethod"),
            nullable=True,
        ),
        sa.Column(
            "delivery_method",
            sa.Enum("COURIER", "PICKUP", name="deliverymethod"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "order_items",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.product_id"],
        ),
        sa.PrimaryKeyConstraint("item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_items")
    op.drop_table("orders")
    # ### end Alembic commands ###
